
client : main.cpp network_client.cpp ../server/request.cpp ../server/message.cpp
	g++ -o client main.cpp network_client.cpp -I../server ../server/request.cpp ../server/message.cpp

.PHONY : clean
clean :
	rm client
