
CXX = g++

CXX_FLAGS = -g -Wall

CXX_INCLUDES = 

CXX_LIBS = -pthread


TARGET = main

OBJECTS = main.o imc.o  \
          request_entry.o request_generator.o\
		  request_centre.o request_handler.o get_handler.o user_message_handler.o group_message_handler.o group_user_handler.o \
		  user_manager.o user.o group_manager.o group.o \
		  request.o message.o

all : $(TARGET)

$(TARGET) : $(OBJECTS)
	$(CXX) $(CXX_FLAGS) -o $@ $(OBJECTS) $(CXX_LIBS)

main.o : main.cpp imc.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

imc.o : imc.cpp request_entry.h request_centre.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

request_entry.o : request_entry.cpp request_entry.h request_generator.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

request_generator.o : request_generator.cpp request_generator.h request_centre.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

request_centre.o : request_centre.cpp request_centre.h request_handler.h request.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

request_handler.o : request_handler.cpp request_handler.h request.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

get_handler.o : get_handler.cpp get_handler.h request_handler.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

user_message_handler.o : user_message_handler.cpp user_message_handler.h request_handler.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

user_manager.o : user_manager.cpp user_manager.h user.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

user.o : user.cpp user.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

group_message_handler.o : group_message_handler.cpp group_message_handler.h 
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

group_user_handler.o : group_user_handler.cpp group_user_handler.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

group_manager.o : group_manager.cpp group_manager.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

group.o : group.cpp group.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

request.o : request.cpp request.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<

message.o : message.cpp message.h
	$(CXX) $(CXX_FLAGS) $(CXX_INCLUDES) -o $@ -c $<




.PHONY : clean
clean : 
	rm *.o
	rm main