
all : main server client

main : main.cpp connection_entry.cpp
	g++ -o main main.cpp connection_entry.cpp -lpthread

server : server.cpp
	g++ -o server server.cpp

client : client.cpp
	g++ -o client client.cpp

.PHONY : clean
clean : 
	rm main server client